name: Container Registry Cleanup

permissions:
  contents: read
  packages: write

on:
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: gbraad-actions/cleanup-untagged-packages@main
        with:
          packages: fedora, centos, almalinux, ubi9, debian, ubuntu, fedora-bootc, centos-bootc, almalinux-bootc
          token: ${{ secrets.PACKAGE_CLEANUP_TOKEN }}
