name: Container Registry Cleanup

permissions:
  contents: read
  packages: write

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: gbraad-actions/cleanup-untagged-packages@main
        with:
          packages: fedora, centos, almalinux, ubi9, debian, ubuntu, fedora-bootc, centos-bootc, almalinux-bootc, fedora-disk, centos-disk, almalinux-disk, fedora-workstation-bootc, fedora-workstation-disk
          token: ${{ secrets.PACKAGE_CLEANUP_TOKEN }}
